const Book = require("../../models/Book");
const provider = require("../providers/gemini.provider");
const { buildEmbeddingText } = require("../utils/embeddingTextBuilder");

class EmbeddingService {
  constructor() {
    this.version = 2;

    this.provider = "gemini-embedding-2";

    this.dimensions = 768;

    this.defaultBatchSize = 10;
  }

  /**
   * Current embedding version.
   */
  getEmbeddingVersion() {
    return this.version;
  }

  /**
   * Current provider.
   */
  getProvider() {
    return this.provider;
  }

  /**
   * Current vector dimensions.
   */
  getDimensions() {
    return this.dimensions;
  }

  /**
   * Create embedding text.
   *
   * Prefer cached searchText generated by BookService.
   * Fall back to embeddingTextBuilder for older books.
   */
  getEmbeddingText(book) {
    if (book.searchText && book.searchText.trim()) {
      return book.searchText;
    }

    return buildEmbeddingText(book);
  }

  /**
   * Fetch a book including hidden fields.
   */
  async getBook(bookId) {
    return Book.findById(bookId).select("+searchText +embedding");
  }

  /**
   * Mark book as processing.
   */
  async markProcessing(bookId) {
    return Book.updateOne(
      { _id: bookId },

      {
        $set: {
          "embeddingMetadata.status": "processing",
        },
      },
    );
  }

  /**
   * Mark completed.
   */
  async markCompleted(bookId, embedding) {
    return Book.updateOne(
      { _id: bookId },

      {
        $set: {
          embedding,

          embeddingMetadata: {
            provider: this.provider,

            version: this.version,

            generatedAt: new Date(),

            dimensions: embedding.length,

            status: "completed",
          },
        },
      },
    );
  }

  /**
   * Mark failed.
   */
  async markFailed(bookId) {
    return Book.updateOne(
      { _id: bookId },

      {
        $set: {
          "embeddingMetadata.status": "failed",
        },
      },
    );
  }

  /**
   * Reset embedding generation.
   */
  async markPending(bookId) {
    return Book.updateOne(
      { _id: bookId },

      {
        $set: {
          "embeddingMetadata.status": "pending",
        },
      },
    );
  }

  /**
   * Generate embedding from a Book object.
   */
  async generateEmbedding(book) {
    const text = this.getEmbeddingText(book);

    if (!text || !text.trim()) {
      throw new Error(`Unable to build embedding text for "${book.title}"`);
    }

    const embedding = await provider.embed(text);

    if (!Array.isArray(embedding)) {
      throw new Error("Embedding provider returned invalid vector.");
    }

    if (embedding.length !== this.dimensions) {
      throw new Error(
        `Expected ${this.dimensions} dimensions but received ${embedding.length}.`,
      );
    }

    return embedding;
  }

  /**
   * Generate embedding directly from raw text.
   */
  async generateEmbeddingFromText(text) {
    if (!text || !text.trim()) {
      throw new Error("Text is required.");
    }

    const embedding = await provider.embed(text);

    if (!Array.isArray(embedding)) {
      throw new Error("Embedding provider returned invalid vector.");
    }

    return embedding;
  }

  /**
   * Generate or regenerate embedding for a single book.
   */
  async updateBookEmbedding(bookId) {
    const book = await this.getBook(bookId);

    if (!book) {
      throw new Error("Book not found.");
    }

    try {
      await this.markProcessing(book._id);

      const embedding = await this.generateEmbedding(book);

      await this.markCompleted(book._id, embedding);

      console.log(`✓ Generated embedding for "${book.title}"`);

      return {
        success: true,

        bookId: book._id,

        title: book.title,

        dimensions: embedding.length,

        status: "completed",
      };
    } catch (error) {
      await this.markFailed(book._id);

      console.error(`✗ Failed embedding: ${book.title}`);

      console.error(error.message);

      throw error;
    }
  }

  /**
   * Process one pending book.
   *
   * Safe entry point for workers.
   */
  async processBook(bookId) {
    const book = await this.getBook(bookId);

    if (!book) {
      return {
        success: false,

        message: "Book not found.",
      };
    }

    if (book.embeddingMetadata?.status === "processing") {
      return {
        success: false,

        message: "Book already being processed.",
      };
    }

    return this.updateBookEmbedding(bookId);
  }
  /**
   * Process all books whose embedding status is "pending".
   */
  async processPendingBooks(limit = this.defaultBatchSize) {
    const books = await Book.find({
      "embeddingMetadata.status": "pending",
    })
      .select("_id title")
      .limit(limit);

    if (!books.length) {
      return {
        success: true,
        processed: 0,
        succeeded: 0,
        failed: 0,
        message: "No pending books found.",
      };
    }

    console.log(`Found ${books.length} pending book(s).`);

    let succeeded = 0;
    let failed = 0;

    const errors = [];

    for (const book of books) {
      try {
        await this.processBook(book._id);

        succeeded++;
      } catch (error) {
        failed++;

        errors.push({
          bookId: book._id,

          title: book.title,

          error: error.message,
        });
      }
    }

    console.log({
      processed: books.length,

      succeeded,

      failed,
    });

    return {
      success: true,

      processed: books.length,

      succeeded,

      failed,

      errors,
    };
  }

  /**
   * Retry books whose previous embedding generation failed.
   */
  async processFailedBooks(limit = this.defaultBatchSize) {
    const books = await Book.find({
      "embeddingMetadata.status": "failed",
    })
      .select("_id title")
      .limit(limit);

    if (!books.length) {
      return {
        success: true,

        processed: 0,

        message: "No failed books found.",
      };
    }

    console.log(`Retrying ${books.length} failed embedding(s).`);

    let succeeded = 0;
    let failed = 0;

    const errors = [];

    for (const book of books) {
      try {
        await this.processBook(book._id);

        succeeded++;
      } catch (error) {
        failed++;

        errors.push({
          bookId: book._id,

          title: book.title,

          error: error.message,
        });
      }
    }

    return {
      success: true,

      processed: books.length,

      succeeded,

      failed,

      errors,
    };
  }

  /**
   * Queue summary.
   */
  async getQueueStatistics() {
    const [pending, processing, completed, failed] = await Promise.all([
      Book.countDocuments({
        "embeddingMetadata.status": "pending",
      }),

      Book.countDocuments({
        "embeddingMetadata.status": "processing",
      }),

      Book.countDocuments({
        "embeddingMetadata.status": "completed",
      }),

      Book.countDocuments({
        "embeddingMetadata.status": "failed",
      }),
    ]);

    return {
      pending,

      processing,

      completed,

      failed,

      total: pending + processing + completed + failed,
    };
  }

  /**
   * Process every pending book.
   */
  async processEntireQueue(batchSize = this.defaultBatchSize) {
    let totalProcessed = 0;
    let totalSucceeded = 0;
    let totalFailed = 0;

    while (true) {
      const result = await this.processPendingBooks(batchSize);

      if (result.processed === 0) {
        break;
      }

      totalProcessed += result.processed;
      totalSucceeded += result.succeeded;
      totalFailed += result.failed;
    }

    return {
      success: true,

      processed: totalProcessed,

      succeeded: totalSucceeded,

      failed: totalFailed,
    };
  }
  /**
   * Regenerate embedding only if required.
   */
  async regenerateIfNeeded(bookId) {
    const book = await this.getBook(bookId);

    if (!book) {
      return null;
    }

    const needsRegeneration =
      !book.embedding ||
      book.embedding.length !== this.dimensions ||
      book.embeddingMetadata?.version !== this.version;

    if (!needsRegeneration) {
      return {
        success: true,

        skipped: true,

        bookId: book._id,

        title: book.title,

        message: "Embedding already up to date.",
      };
    }

    await this.markPending(book._id);

    return this.processBook(book._id);
  }

  /**
   * Regenerate embeddings for every book.
   */
  async regenerateAllEmbeddings(batchSize = this.defaultBatchSize) {
    console.log("Resetting all books to pending...");

    await Book.updateMany(
      {},
      {
        $set: {
          "embeddingMetadata.status": "pending",
        },
      },
    );

    console.log("Starting regeneration...");

    return this.processEntireQueue(batchSize);
  }

  /**
   * Reset every embedding back to pending.
   */
  async resetAllToPending() {
    const result = await Book.updateMany(
      {},
      {
        $set: {
          "embeddingMetadata.status": "pending",
        },
      },
    );

    return {
      success: true,

      modified: result.modifiedCount,
    };
  }

  /**
   * Remove embeddings from every book.
   *
   * Useful when switching providers or dimensions.
   */
  async clearEmbeddings() {
    const result = await Book.updateMany(
      {},
      {
        $unset: {
          embedding: "",
        },
        $set: {
          "embeddingMetadata.status": "pending",
          "embeddingMetadata.generatedAt": null,
          "embeddingMetadata.dimensions": this.dimensions,
          "embeddingMetadata.provider": this.provider,
          "embeddingMetadata.version": this.version,
        },
      },
    );

    return {
      success: true,

      modified: result.modifiedCount,
    };
  }

  /**
   * Health information.
   */
  async health() {
    const queue = await this.getQueueStatistics();

    return {
      provider: this.provider,

      version: this.version,

      dimensions: this.dimensions,

      queue,
    };
  }

  /**
   * Service information.
   */
  info() {
    return {
      provider: this.provider,

      version: this.version,

      dimensions: this.dimensions,

      batchSize: this.defaultBatchSize,
    };
  }
}

module.exports = new EmbeddingService();
